name: "Golang Static Analysis Checker"
description: "A configurable static code analysis checker for Golang"
author: "danhunsaker"
inputs:
  run:
    description: "execute comma-separated command(s). [errcheck/fmt/imports/ineffassign/lint/misspell/sec/shadow/staticcheck/vet]"
    required: true
  directory:
    description: "action working directory."
    default: "."
    required: false
  comment:
    description: "send comment to PR (or commit) if true."
    default: "true"
    required: false
  token:
    description: "GitHub token. this is required when comment is true."
    default: ""
    required: false
  flags:
    description: "add flags"
    default: ""
    required: false
  ignore-defer:
    description: "if this is true, do not detect 'defer' with error. This is only valid when run is errcheck."
    default: "false"
    required: false
  max-complexity:
    description: "the highest cyclomatic complexity to ignore with gocyclo"
    default: "15"
    required: false
  go-private-mod-username:
    description: "login username for go dependencies from private repos"
    default: ""
    required: false
  go-private-mod-password:
    description: "password or GitHub personal access token for go dependencies from private repos"
    default: ""
    required: false
  go-private-mod-org-path:
    description: "git private organization url. eg. github.com/my-org"
    default: ""
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.run }}
    - ${{ inputs.directory }}
    - ${{ inputs.comment }}
    - ${{ inputs.token }}
    - ${{ inputs.flags }}
    - ${{ inputs.ignore-defer }}
    - ${{ inputs.max-complexity }}
    - ${{ inputs.go-private-mod-username }}
    - ${{ inputs.go-private-mod-password }}
    - ${{ inputs.go-private-mod-org-path }}
branding:
  icon: "alert-triangle"
  color: "yellow"
